ZDOTDIR=${ZDOTDIR:-$HOME/.zsh}
export GPG_TTY=$TTY
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CONFIG_HOME=$HOME/.config
export XDG_STATE_HOME=$HOME/.local/state
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export XDG_CONFIG_DIRS=/etc/xdg
export XDG_CACHE_HOME=$HOME/.cache
#export GNUPGHOME=${XDG_DATA_HOME:-$HOME/.local/share}/gnpg
export GOPATH=$XDG_DATA_HOME/go
export NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm
export CARGO_HOME=$XDG_DATA_HOME/cargo   # ln -s $HOME/.local/bin $XDG_DATA_HOME/cargo/bin
export GRADLE_USER_HOME=$XDG_DATA_HOME/gradle
export GTK2_RC_FILES=$XDG_CONFIG_HOME/gtk-2.0/gtkrc
export SCREENRC=$XDG_CONFIG_HOME/screenrc
export CUDA_CACHE_PATH=$XDG_CACHE_HOME/nv
export _GL_SHADER_DISK_CACHE_PATH=$XDG_CACHE_HOME/nv
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java -Dawt.useSystemAAFontSettings=on"
export QT_QPA_PLATFORMTHEME=qt5ct
#export QT_STYLE_OVERRIDE=kvantum
setopt NO_GLOBAL_RCS
