Net/ThemeName "Qogir-Round-Dark"
Net/IconThemeName "Qogir-Dark"
Gtk/CursorThemeName "Qogir-Dark"
Net/EnableEventSounds 0
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintfull"
Xft/RGBA "rgb"
